lrstanley/helm-charts

charts/autodelete-discord/Chart.yaml

- upgrade chart autodelete-discord from `0.1.2` to `0.2.0`
- upgrade `appVersion` from `0.0.0` to `1.1.0`
auto-created from [helm-version-updater](https://github.com/lrstanley/helm-charts/actions/workflows/helm-version-updater.yml) action

upgrade chart autodelete-discord to 0.2.0

---

charts/autodelete-discord/Chart.yaml

Updating chart `autodelete-discord`:
- Bumping **version** from `0.4.1` to `0.5.0`.
- Bumping **appVersion** from `1.1.0` to `1.2.0`.

update chart autodelete-discord from 0.4.1 to 0.5.0

---

.github/workflows/helm-docs.yml

- Bumping **version** from [`1.11.2`](https://github.com/norwoodj/helm-docs/releases/tag/1.11.2) to [`1.11.3`](https://github.com/norwoodj/helm-docs/releases/tag/1.11.3).
Release notes: [link](https://github.com/norwoodj/helm-docs/releases/tag/1.11.3)

update helm-docs from 1.11.2 to 1.11.3

---

.github/workflows/release.yml

- Bumping **version** from [`v3.13.1`](https://github.com/helm/helm/releases/tag/v3.13.1) to [`v3.13.2`](https://github.com/helm/helm/releases/tag/v3.13.2).
Release notes: [link](https://github.com/helm/helm/releases/tag/v3.13.2)

update helm from v3.13.1 to v3.13.2

---

charts/pgweb/Chart.yaml

Updating chart `pgweb`:
- Bumping **version** from `1.0.5` to `1.0.6`.
- Bumping **appVersion** from `0.14.0` to `0.14.2`.

update chart pgweb from 1.0.5 to 1.0.6

---

charts/outline/Chart.yaml

- Bumping **version** from `1.1.0` to `1.2.0`.
- Bumping **appVersion** from `0.72.2` to `0.73.1`.

update chart outline from 1.1.0 to 1.2.0

---

charts/outline/Chart.yaml

- Bumping **version** from `1.3.4` to `1.4.0`.
- Bumping **appVersion** from `0.73.1` to `0.74.0`.

update chart outline from 1.3.4 to 1.4.0

---

charts/autodelete-discord/Chart.yaml

Updating chart `autodelete-discord`:
- Bumping **version** from `0.6.1` to `0.6.2`.
- Bumping **appVersion** from `1.2.0` to `1.2.1`.

update chart autodelete-discord from 0.6.1 to 0.6.2

---

.github/workflows/release.yml

- Bumping **version** from [`v3.13.2`](https://github.com/helm/helm/releases/tag/v3.13.2) to [`v3.13.3`](https://github.com/helm/helm/releases/tag/v3.13.3).
Release notes: [link](https://github.com/helm/helm/releases/tag/v3.13.3)

update helm from v3.13.2 to v3.13.3

---

.github/workflows/helm-docs.yml

- Bumping **version** from [`v1.11.3`](https://github.com/norwoodj/helm-docs/releases/tag/v1.11.3) to [`v1.12.0`](https://github.com/norwoodj/helm-docs/releases/tag/v1.12.0).
Release notes: [link](https://github.com/norwoodj/helm-docs/releases/tag/v1.12.0)

update helm-docs from v1.11.3 to v1.12.0

---

.github/workflows/release.yml

- Bumping **version** from [`v3.13.3`](https://github.com/helm/helm/releases/tag/v3.13.3) to [`v3.14.0`](https://github.com/helm/helm/releases/tag/v3.14.0).
Release notes: [link](https://github.com/helm/helm/releases/tag/v3.14.0)

update helm from v3.13.3 to v3.14.0

---

charts/outline/Chart.yaml

- Bumping **version** from `1.4.0` to `1.5.0`.
- Bumping **appVersion** from `0.74.0` to `0.75.0`.

update chart outline from 1.4.0 to 1.5.0

---

.github/workflows/release.yml

- Bumping **version** from [`v3.14.0`](https://github.com/helm/helm/releases/tag/v3.14.0) to [`v3.14.1`](https://github.com/helm/helm/releases/tag/v3.14.1).
Release notes: [link](https://github.com/helm/helm/releases/tag/v3.14.1)

update helm from v3.14.0 to v3.14.1

---

.github/workflows/release.yml

- Bumping **version** from [`v3.14.1`](https://github.com/helm/helm/releases/tag/v3.14.1) to [`v3.14.2`](https://github.com/helm/helm/releases/tag/v3.14.2).
Release notes: [link](https://github.com/helm/helm/releases/tag/v3.14.2)

update helm from v3.14.1 to v3.14.2

---

.github/workflows/helm-docs.yml

- Bumping **version** from [`v1.12.0`](https://github.com/norwoodj/helm-docs/releases/tag/v1.12.0) to [`v1.13.0`](https://github.com/norwoodj/helm-docs/releases/tag/v1.13.0).
Release notes: [link](https://github.com/norwoodj/helm-docs/releases/tag/v1.13.0)

update helm-docs from v1.12.0 to v1.13.0

---

.github/workflows/release.yml

- Bumping **version** from [`v3.14.2`](https://github.com/helm/helm/releases/tag/v3.14.2) to [`v3.14.3`](https://github.com/helm/helm/releases/tag/v3.14.3).
Release notes: [link](https://github.com/helm/helm/releases/tag/v3.14.3)

update helm from v3.14.2 to v3.14.3

---

.github/workflows/release.yml

- Bumping **version** from [`v3.14.3`](https://github.com/helm/helm/releases/tag/v3.14.3) to [`v3.14.4`](https://github.com/helm/helm/releases/tag/v3.14.4).
Release notes: [link](https://github.com/helm/helm/releases/tag/v3.14.4)

update helm from v3.14.3 to v3.14.4

---

.github/workflows/helm-docs.yml

- Bumping **version** from [`v1.13.0`](https://github.com/norwoodj/helm-docs/releases/tag/v1.13.0) to [`v1.13.1`](https://github.com/norwoodj/helm-docs/releases/tag/v1.13.1).
Release notes: [link](https://github.com/norwoodj/helm-docs/releases/tag/v1.13.1)

update helm-docs from v1.13.0 to v1.13.1

---

charts/outline/Chart.yaml

- Bumping **version** from `1.5.1` to `1.6.0`.
- Bumping **appVersion** from `0.75.2` to `0.76.1`.

update chart outline from 1.5.1 to 1.6.0

---

charts/outline/Chart.yaml

- Bumping **version** from `1.6.0` to `1.7.0`.
- Bumping **appVersion** from `0.76.1` to `0.77.0`.

update chart outline from 1.6.0 to 1.7.0

---

.github/workflows/release.yml

- Bumping **version** from [`v3.14.4`](https://github.com/helm/helm/releases/tag/v3.14.4) to [`v3.15.0`](https://github.com/helm/helm/releases/tag/v3.15.0).
Release notes: [link](https://github.com/helm/helm/releases/tag/v3.15.0)

update helm from v3.14.4 to v3.15.0

---

charts/outline/Chart.yaml

- Bumping **version** from `1.7.0` to `1.7.1`.
- Bumping **appVersion** from `0.77.0` to `0.77.1`.

update chart outline from 1.7.0 to 1.7.1

---

.github/workflows/release.yml

- Bumping **version** from [`v3.15.2`](https://github.com/helm/helm/releases/tag/v3.15.2) to [`v3.15.3`](https://github.com/helm/helm/releases/tag/v3.15.3).
Release notes: [link](https://github.com/helm/helm/releases/tag/v3.15.3)

update helm from v3.15.2 to v3.15.3

---

.github/workflows/helm-docs.yml

- Bumping **version** from [`v1.13.1`](https://github.com/norwoodj/helm-docs/releases/tag/v1.13.1) to [`v1.14.2`](https://github.com/norwoodj/helm-docs/releases/tag/v1.14.2).
Release notes: [link](https://github.com/norwoodj/helm-docs/releases/tag/v1.14.2)

update helm-docs from v1.13.1 to v1.14.2

---

charts/outline/Chart.yaml

- Bumping **version** from `1.7.1` to `1.7.2`.
- Bumping **appVersion** from `0.77.1` to `0.77.2`.

update chart outline from 1.7.1 to 1.7.2

---

.github/workflows/release.yml

- Bumping **version** from [`v3.15.3`](https://github.com/helm/helm/releases/tag/v3.15.3) to [`v3.15.4`](https://github.com/helm/helm/releases/tag/v3.15.4).
Release notes: [link](https://github.com/helm/helm/releases/tag/v3.15.4)

update helm from v3.15.3 to v3.15.4

---

charts/pgweb/Chart.yaml

Updating chart `pgweb`:
- Bumping **version** from `1.1.0` to `1.2.0`.
- Bumping **appVersion** from `0.15.0` to `0.16.1`.

update chart pgweb from 1.1.0 to 1.2.0

---

charts/pgweb/Chart.yaml

Updating chart `pgweb`:
- Bumping **version** from `1.2.0` to `1.2.1`.
- Bumping **appVersion** from `0.16.1` to `0.16.2`.

update chart pgweb from 1.2.0 to 1.2.1

---

.github/workflows/release.yml

- Bumping **version** from [`v3.15.4`](https://github.com/helm/helm/releases/tag/v3.15.4) to [`v3.18.0`](https://github.com/helm/helm/releases/tag/v3.18.0).
Release notes: [link](https://github.com/helm/helm/releases/tag/v3.18.0)

update helm from v3.15.4 to v3.18.0

---

charts/outline/templates/deployment.yaml
charts/outline/values.yaml

This pull request includes changes to the `charts/outline` Helm chart to make the number of replicas configurable. 
Closes #59

fix(outline): support for multiple replicas

---

.github/workflows/release.yml

- Bumping **version** from [`v3.18.0`](https://github.com/helm/helm/releases/tag/v3.18.0) to [`v3.18.3`](https://github.com/helm/helm/releases/tag/v3.18.3).
Release notes: [link](https://github.com/helm/helm/releases/tag/v3.18.3)

update helm from v3.18.0 to v3.18.3
